# Generated by Django 4.2.3 on 2023-07-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0012_answer_confirmation"),
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="done",
            field=models.ManyToManyField(
                blank=True, related_name="answers_done", to="challenge.answer"
            ),
        ),
    ]
