# Generated by Django 4.2.3 on 2023-07-14 21:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0003_alter_place_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
