# Generated by Django 4.2.3 on 2023-07-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0005_challenge_remove_place_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="place",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                to="challenge.place",
            ),
            preserve_default=False,
        ),
    ]
