# Generated by Django 4.2.3 on 2023-07-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0007_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="cordinates",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
