# Generated by Django 4.2.3 on 2023-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0008_challenge_cordinates"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Question",
            new_name="Answer",
        ),
        migrations.AlterField(
            model_name="challenge",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
