# Generated by Django 4.2.3 on 2023-07-15 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0009_rename_question_answer_alter_challenge_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challenge",
            old_name="title",
            new_name="quiz",
        ),
    ]
