# Generated by Django 4.2.3 on 2023-07-15 22:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0010_rename_title_challenge_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
