# Generated by Django 4.2.3 on 2023-07-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0011_alter_challenge_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="confirmation",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
